
services:
  # Servidor principal da API (ServeRest)
  serverest:
    # CORREÇÃO AQUI: o nome da imagem é 'serverest'
    image: serverest 
    ports:
      - "3000:3000"

  flows:
    image: "pactumjs/flows:latest"
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=mongo"
    depends_on:
      - mongo 

  mongo:
    image: "mongo:4.2.12"