version: "3.9"
services:
  # Servidor principal da API (ServeRest)
  serverest:
    image: serverest/serverest
    ports:
      - "3000:3000"

  # Servidor de Flows do Pactum (O que exige a porta 8080)
  flows:
    image: "pactumjs/flows:latest"
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=mongo"
    depends_on:
      - mongo 

  # Banco de Dados
  mongo:
    image: "mongo:4.2.12"